namespace :app do
  
  task :ensure_development_environment => :environment do
    if Rails.env.production?
      raise "\nCan't Drop production data"
    end
  end
  
  
  desc "Reset"
  task :reset => [:ensure_development_environment, "db:drop", "db:create", "db:migrate", "db:seed", "app:populate"]
  
  
  desc "Populate databse with development data."
  task :populate => :environment do
    #Users
    [
      {:company => "Darden",        :date_joined => Date.today,     :email => "darden@email.com",       :password => "password",  :password_confirmation => "password" },
      {:company => "OSI",           :date_joined => 5.months.ago,   :email => "osi@email.com",          :password => "password",  :password_confirmation => "password" },
    ].each do |attributes|
      User.find_or_create_by_company(attributes)
    end
    
    #Restaurants for Darden
    [
      {:name => "Olive Garden",       :type => "Italian",              :user_id => 1,    :description => "Olive Garden welcomed its first guests in 1982. Nearly 30 years later, Olive Garden remains committed to its purpose of Hospitaliano! - providing 100% guest delight through a genuine Italian dining experience. \n Italy serves as the inspiration for the brand, from its menus to its award-winning wine list to the Tuscan farmhouse design of its restaurants. Most of all, Olive Garden is inspired by the warmth and genuine hospitality of the Italian people, as well as the importance of family in their culture. \n This passion for Italy led to the establishment of Olive Garden's Culinary Institute of Tuscany in 1999. More than 1,200 Olive Garden managers and team members have been welcomed to the CIT as part of an internal cultural immersion program designed to inspire, motivate and educate team members."},
      {:name => "Red Lobster",        :type => "Sea Food",             :user_id => 1,    :description => "Company founder Bill Darden opened his first restaurant, The Green Frog, at age 19. Thirty years later, Bill brought his passion for seafood to Lakeland, Fla., where he debuted the first Red Lobster in 1968. Bill’s vision was to create a place where America could go for seafood for generations and where employees could fulfill their aspirations.\nAs it grew into a national brand, Red Lobster introduced guests to fresh dishes such as popcorn shrimp, calamari, snow crab and lobster – often for the first time. Over the years, the brand’s passion for fresh, delicious seafood has kept Red Lobster evolving. The restaurant introduced an award-winning Today’s Fresh Fish Menu, installed wood-fire grills in every restaurant in North America, trained staff to become seafood experts and most recently launched a new restaurant design, inspired by the New England coast."},
      {:name => "LongHorn",           :type => "Steakhouse",           :user_id => 1,    :description => "LongHorn Steakhouse opened its first restaurant in Atlanta, Ga., in 1981 and has grown steadily ever since. But that first restaurant almost didn’t survive its initial year in business until good fortune fell from the sky in the form of a freak snowstorm in Atlanta. After stranded motorists (including a local restaurant critic) sought refuge inside, word quickly spread about the delicious steaks and genuine western hospitality.\nToday, LongHorn welcomes guests into a warm, relaxing atmosphere reminiscent of a Western rancher’s home where friendly, attentive servers help them unwind and savor a great steakhouse meal. Known for its passion for grilling inspired by the American West, LongHorn proudly serves steaks, chicken and fish that are always fresh, never frozen."},
      {:name => "The Capital Grille", :type => "Grill",                :user_id => 1,    :description => "Founded in 1990 in Providence, RI, The Capital Grille is a fine-dining restaurant known for its dry-aged steaks, fresh seafood, award-winning wine list and personalized, professional service in an atmosphere of relaxed elegance. Routinely recognized by Zagat, the brand has also received the American Culinary Federation’s “Achievement of Excellence Award” and was named one of the top 50 American restaurants in Open Table’s Diners’ Choice Awards. In addition, The Capital Grille has won an unprecedented number of “Best of Awards of Excellence” from Wine Spectator magazine and offers more than 350 New and Old World wine selections, including a Captain’s List of some of the world’s most highly allocated and sought-after wines."},
      {:name => "Bahama Breeze",      :type => "Carribbean",           :user_id => 1,    :description => "Bahama Breeze brings you the feeling of a Caribbean escape, offering the food, drink and atmosphere you’d find in the islands. Introduced in 1996, the brand is known nationally for popularizing many Caribbean-inspired foods in the United States. The Bahama Breeze menu features familiar favorites, including seafood, chicken and steak, accented with the flavorful and colorful ingredients you’d find in the islands and reflecting the growing popularity of Caribbean and Latin flavors."},
      {:name => "Seasons 52",         :type => "Fresh Grill Wine Bar", :user_id => 1,    :description => "Seasons 52 is a fresh grill and wine bar that invites guests to discover the sensational flavors of a seasonally inspired menu and award winning international wine list in a casually sophisticated adult ambiance. Introduced in 2003, the brand promises guests the freedom to indulge, while simultaneously eating well and feeling good about themselves, by featuring foods that are thoughtfully prepared and intriguing to the palate.\nSeasons 52 offers a variety of experiences. Its private dining rooms create the ideal environment for many social and business events. The Chef’s Table provides a unique and intimate setting for chef-hosted, customizable food and wine pairing events. And the piano bar, featuring live music every night, is a great place to unwind and enjoy the warm, inviting ambiance."},
    ].each do |attributes|
      Restaurant.find_or_create_by_name(attributes)
    end    
    
    #Restaurants for OSI
    [
      {:name => "OUTBACK",    :type => "Steakhouse",      :user_id => 2,    :description => "Outback Steakhouse is an Australian themed steakhouse restaurant. Although beef and steak items make up a good portion of the menu, the concept offers a variety of chicken, ribs, seafood, and pasta dishes. The Company's strategy is to differentiate its restaurants by emphasizing consistently high-quality food and service, generous portions at moderate prices and a casual atmosphere suggestive of the Australian Outback."},
      {:name => "CARRABBA'S", :type => "Italian",         :user_id => 2,    :description => "We don't mean diners, gourmands or bon vivants. We're two big Sicilian boys from Texas who love to cook and eat. We love the Sicilian food our parents and grandparents cooked. We love the Creole and Southern food our family members picked up passing through Louisiana and stepping off the boat right on the dock in Galveston. And we love the Western food that's just part of being in Texas.\nFood, you see, isn't only about food. It's not some big secret. It's something that just happens when all of our interconnected families get together-the Carrabbas and the Mandolas, plus anybody with enough good sense to marry in. You may be poor, went the saying a mere generation ago, but you'll never be hungry.
      Food is part of us because that's how we were raised; food was present at births, christenings, weddings, graduations and funerals. Food is what reminded us we were family. To this day, whenever one family member meets another and starts talking about something or someplace, the first question has to be, \"Whadya eat?\"\nOur Gulf Coast experience is about the place where all of our ancestors came to build their lives. They called it America! And they didn't just mean Ellis Island, or Little Italy in New York, or the North End of Boston or South Philly. They meant the whole damn place, wherever it began and ended, which of course nobody much knew. And it meant an idea too, a big promise in the air during the hard times in Sicily that if you sacrificed just about everything and pretty near worked yourself to death, you could have something a little better. Which, after all, was exactly what you did in the Old Country-without any promise at all.\nSo they came, ship after ship full of them. Full of us. And all the while, there were other ships filled with other people, speaking different languages. In America, we would come to know them all. And talk with them all. And wrestle with them all. And, in some cases, cook with them all. We kept on being who we are, sure enough, but after a while we were something different, too. Something entirely new.\nSo give us a break here. Don't go picking over our Grandma's and Mamma's and Aunt's and Uncle's recipes, whining about this not being the way they did it at your house. Great! We'll go to your house, this is the way the old folks taught the young folks. This is the way we remember things tasting. And this is what it all comes down to-with generous sprinklings of life, love and oregano-for two big Sicilian boys from Texas who love to cook and eat."},
      {:name => "BONEFISH",   :type => "Grill",           :user_id => 2,    :description => "When you walk through our doors, you may notice the chef-coat service or wine display. But we’ve left the stuffiness and unpronounceable menu out. Our polished casual setting helps you relax and celebrate – even if the occasion you’re celebrating is just dinner.\nIn here, the specials don’t stop at the food. Here, special is the feel of a big city bar that’s not far from home. It’s a wood-burning grill that swaps out boredom and routine for a dinner that opens your eyes. It’s chef-coat service that’s not about being stuffy, but all about knowing what you need. It’s feeling good about the food, the people and the bill each time you walk through the door. Because at Bonefish Grill, special isn’t something that comes around once a year. It’s something you’ll find here any night of the week. No matter what the reason is for your visit, we’re ready to share the BFG experience with you.\nSo don’t let today get away®. Visit Bonefish Grill tonight."},
      {:name => "Flemming's", :type => "Steakhouse",      :user_id => 2,    :description => "Since the first Fleming's Prime Steakhouse & Wine Bar opened in 1998, we've raised the standard of excellence for steakhouses to a whole new level, winning awards all over the country for outstanding food, wine and service.\nStylish, contemporary dining is the hallmark of Fleming's. As our name implies, our menu features the finest in prime beef, augmented by a tempting variety of chops, seafood, chicken, generous salads, inventive side orders and indulgent desserts. Our celebrated wine list, known as the Fleming's 100, boasts some of the finest wines in the world, all available by the glass.\nOur goal is to provide an ongoing celebration of exceptional food and wine, in the company of friends and family. We think you'll find the atmosphere inviting, the spirit generous and joyful, and the overall experience one you won't soon forget."},
      {:name => "Roy's",      :type => "Hawaiian",        :user_id => 2,    :description => "In Hawaii, there are two things of equal importance—food and the \"aloha\" spirit. The blending of these two dynamic principles is how Roy’s Hawaiian Fusion® Cuisine was born. European techniques and Asian cuisine meet Hawaiian hospitality to create a fine dining experience unlike any other. Where the \"aloha\" style of service comes straight from the heart, and where any occasion becomes an unforgettable evening."},
    ].each do |attributes|
      Restaurant.find_or_create_by_name(attributes)
    end
    

    
  end
  
  
end